/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IVictim, IVictimInterface } from "../../src/IVictim";

const _abi = [
  {
    inputs: [],
    name: "drainedMethod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVictim__factory {
  static readonly abi = _abi;
  static createInterface(): IVictimInterface {
    return new utils.Interface(_abi) as IVictimInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVictim {
    return new Contract(address, _abi, signerOrProvider) as IVictim;
  }
}
