/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface DrainerInterface extends utils.Interface {
  functions: {
    "drain(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "drain" | "drain(address,uint256)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "drain",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drain(address,uint256)",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "drain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drain(address,uint256)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Drainer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DrainerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    drain(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "drain(address,uint256)"(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  drain(
    victim: string,
    cycles: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "drain(address,uint256)"(
    victim: string,
    cycles: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    drain(
      victim: string,
      cycles: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "drain(address,uint256)"(
      victim: string,
      cycles: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    drain(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "drain(address,uint256)"(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    drain(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "drain(address,uint256)"(
      victim: string,
      cycles: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
