/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as drainerContractSol from "./drainerContract.sol";
export type { drainerContractSol };
export type { MockERC20 } from "./MockERC20";
